# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- other

pool:
  vmImage: ubuntu-latest

steps:

- checkout: self
  fetchDepth: 0
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'ochanya123'
    scannerMode: 'Other'
    extraProperties: |
      # Additional properties that will be passed to the scanner, 
      # Put one key=value per line, example:
      # sonar.exclusions=**/*.bin
      sonar.projectKey=elizaidoko_spring-petclinic
      sonar.projectName=spring-petclinic
   
    
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- task: Docker@2
  inputs:
    containerRegistry: 'Docker-service'
    repository: 'elizaidoko/test'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: 'whatever'

- task: Docker@2
  inputs:
    containerRegistry: 'Docker-service'
    repository: 'elizaidoko/test'
    command: 'push'
    tags: 'whatever'
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    appType: 'webAppContainer'
    WebAppName: 'petclini'
    DockerNamespace: 'elizaidoko'
    DockerRepository: 'test'
    DockerImageTag: 'whatever'
    StartupCommand: 'java -jar target/spring-petclinic-3.0.0-SNAPSHOT.jar'